version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      despical-libraries:
        patterns:
          - "dev.despical:commons"
          - "dev.despical:command-framework"
          - "dev.despical:inventory-framework"
          - "dev.despical:file-items"
      gradle-build-tooling:
        patterns:
          - "gradle"
          - "com.gradleup.shadow*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
