name: TNTRun
version: ${project.version}
description: The ultimate TNT Run plugin.
author: Despical

main: me.despical.tntrun.Main
api-version: 1.13

softdepend:
  - PlaceholderAPI
  - Multiverse-Core
  - WorldGuard
  - MultiWorld
  - Oraxen

permissions:
  tntrun.admin.*:
    default: op
    children:
      tntrun.admin: true
      tntrun.admin.create: true
      tntrun.admin.delete: true
      tntrun.admin.edit: true
      tntrun.admin.list: true
      tntrun.admin.help: true
      tntrun.admin.forcestart: true
      tntrun.admin.stop: true
      tntrun.admin.sign.create: true
      tntrun.admin.sign.break: true
      tntrun.admin.reload: true
      tntrun.command.override: true